#:property UseAppHost=false

using System.Text;
using System.Text.RegularExpressions;

/// <summary>
/// Writes the skeleton of one feature vertical across the four layers.
/// </summary>
/// <remarks>
/// <para>
/// What it emits is shape, never behaviour: folders, file names, namespaces, base types and the
/// members a layer's conventions require. Every invariant it satisfies is one an architecture rule
/// already checks — namespace equals project name plus folder path, one public type per file named
/// exactly like the file, a sealed aggregate root, a repository contract under
/// <c>Repositories/</c> — so the thing it saves is the typing, and the thing it cannot save is the
/// thinking.
/// </para>
/// <para>
/// <b>It creates files and edits none.</b> A vertical does not compose until its module
/// registrations are written by hand, and that is deliberate everywhere else in this repository:
/// registration is opt-in per feature so a feature nobody composes is registered nowhere and the
/// absence is visible in the file. A generator reaching into a composition root would take that
/// property away. So the wiring is printed instead, alongside the closed lists the new feature
/// lands in.
/// </para>
/// <para>
/// <b>The product prefix is read off the tree, not assumed.</b> A derived project is generated with
/// its own name, so this reads the prefix from the directory holding the domain project. A tool
/// that hard-coded one would work only in the repository it was written in, which is the one place
/// it is least needed.
/// </para>
/// <example>
/// <code>
/// dotnet run Tools/NewFeature.cs Widgets Widget
/// dotnet run Tools/NewFeature.cs --self-test
/// </code>
/// </example>
/// </remarks>
internal static class NewFeature
{
    private static readonly Regex PascalCase = new(@"^[A-Z][A-Za-z0-9]*$");

    /// <summary>One emitted file: where it goes, and what goes in it.</summary>
    private sealed record Emission(string Path, string Content);

    private static int Main(string[] args)
    {
        if (Array.IndexOf(args, "--self-test") >= 0)
        {
            return SelfTest();
        }

        string[] positional = [.. args.Where(argument => !argument.StartsWith("--", StringComparison.Ordinal))];

        if (positional.Length is < 2 or > 3)
        {
            Console.Error.WriteLine(
                "Usage: dotnet run Tools/NewFeature.cs <Feature> <Aggregate> [root]\n" +
                "  <Feature>   the folder, in the plural — Widgets\n" +
                "  <Aggregate> the type, in the singular — Widget");

            return 1;
        }

        string feature = positional[0];
        string aggregate = positional[1];
        string root = Resolve(positional.Length == 3 ? positional[2] : ".");

        foreach (string problem in NameProblems(feature, aggregate))
        {
            Console.Error.WriteLine(problem);
        }

        if (NameProblems(feature, aggregate).Count > 0)
        {
            return 1;
        }

        string prefix = ProductPrefix(root);
        var emissions = Plan(prefix, feature, aggregate);

        string[] existing = [.. emissions
            .Select(emission => System.IO.Path.Combine(root, emission.Path))
            .Where(File.Exists)];

        if (existing.Length > 0)
        {
            Console.Error.WriteLine(
                $"Refusing to write: {existing.Length} of these files already exist. A feature is "
                + "scaffolded once; after that it is edited.");

            foreach (string path in existing)
            {
                Console.Error.WriteLine($"  {System.IO.Path.GetRelativePath(root, path)}");
            }

            return 1;
        }

        foreach (var emission in emissions)
        {
            Write(System.IO.Path.Combine(root, emission.Path), emission.Content);
        }

        Report(prefix, feature, aggregate, emissions);

        return 0;
    }

    /// <summary>
    /// The prefix every project of this tree shares, read off the directory that holds the domain
    /// project.
    /// </summary>
    /// <exception cref="InvalidOperationException">No such directory, so this is not that tree.</exception>
    private static string ProductPrefix(string root)
    {
        string domain = System.IO.Path.Combine(root, "Src", "Domain");

        string? found = Directory.Exists(domain)
            ? Directory.EnumerateDirectories(domain)
                .Select(directory => new DirectoryInfo(directory).Name)
                .FirstOrDefault(name => name.EndsWith(".Domain", StringComparison.Ordinal))
            : null;

        return found is null
            ? throw new InvalidOperationException(
                $"No '<Prefix>.Domain' project under '{domain}'. Run this from a tree generated by "
                + "this template, or pass its root as the third argument.")
            : found[..^".Domain".Length];
    }

    private static List<string> NameProblems(string feature, string aggregate)
    {
        var problems = new List<string>();

        if (!PascalCase.IsMatch(feature))
        {
            problems.Add($"'{feature}' is not a folder name: <Feature> is PascalCase and plural, e.g. Widgets.");
        }

        if (!PascalCase.IsMatch(aggregate))
        {
            problems.Add($"'{aggregate}' is not a type name: <Aggregate> is PascalCase and singular, e.g. Widget.");
        }

        // The convention this repository states: folders carry the feature, file and type names
        // carry the aggregate. Equal names make the two indistinguishable in every path below.
        if (string.Equals(feature, aggregate, StringComparison.Ordinal))
        {
            problems.Add(
                $"<Feature> and <Aggregate> are both '{feature}'. The folder is the plural and the "
                + "type is the singular — Widgets and Widget — because the layout rules read them apart.");
        }

        return problems;
    }

    private static void Write(string path, string content)
    {
        Directory.CreateDirectory(System.IO.Path.GetDirectoryName(path)!);

        // A .cs file in this tree carries a UTF-8 BOM and LF endings; the build turns a missing BOM
        // into an error whose message does not mention it.
        File.WriteAllText(path, content.ReplaceLineEndings("\n"), new UTF8Encoding(encoderShouldEmitUTF8Identifier: true));
    }

    private static string Resolve(string path) => System.IO.Path.GetFullPath(path);

    /// <summary>Every file the vertical starts with, in the order a reader meets the layers.</summary>
    private static List<Emission> Plan(string prefix, string feature, string aggregate)
    {
        var emissions = new List<Emission>();

        void Add(string project, string relative, string template) =>
            emissions.Add(new Emission(
                $"{project}/Features/{feature}/{relative}"
                    .Replace("%A%", aggregate, StringComparison.Ordinal)
                    .Replace("%F%", feature, StringComparison.Ordinal),
                Fill(template, prefix, feature, aggregate)));

        string domain = $"Src/Domain/{prefix}.Domain";
        string application = $"Src/Application/{prefix}.Application";
        string persistence = $"Src/Infrastructure/{prefix}.Infrastructure.Persistence";
        string api = $"Src/Presentation/{prefix}.Api";

        Add(domain, "Entities/%A%.cs", Templates.Aggregate);
        Add(domain, "Repositories/I%A%Repository.cs", Templates.RepositoryPort);

        Add(application, "Errors/%A%Errors.cs", Templates.Errors);
        Add(application, "Dtos/%A%Dto.cs", Templates.Dto);
        Add(application, "Ports/%A%Queries/I%A%Queries.cs", Templates.QueriesPort);
        Add(application, "Services/I%A%Service.cs", Templates.ServicePort);
        Add(application, "Services/%A%Service.cs", Templates.Service);
        Add(application, "UseCases/Queries/Get%A%/IGet%A%UseCase.cs", Templates.GetUseCasePort);
        Add(application, "UseCases/Queries/Get%A%/Get%A%UseCase.cs", Templates.GetUseCase);
        Add(application, "UseCases/Commands/Create%A%/ICreate%A%UseCase.cs", Templates.CreateUseCasePort);
        Add(application, "UseCases/Commands/Create%A%/Create%A%UseCase.cs", Templates.CreateUseCase);
        Add(application, "UseCases/Commands/Delete%A%/Delete%A%Command.cs", Templates.DeleteCommand);
        Add(application, "UseCases/Commands/Delete%A%/IDelete%A%UseCase.cs", Templates.DeleteUseCasePort);
        Add(application, "UseCases/Commands/Delete%A%/Delete%A%UseCase.cs", Templates.DeleteUseCase);
        Add(application, "UseCases/Commands/Delete%A%/Delete%A%CommandValidator.cs", Templates.DeleteValidator);

        Add(persistence, "Models/%A%Record.cs", Templates.Record);
        Add(persistence, "Configurations/%A%RecordConfiguration.cs", Templates.Configuration);
        Add(persistence, "Mapping/I%A%Mapper.cs", Templates.MapperPort);
        Add(persistence, "Mapping/%A%Mapper.cs", Templates.Mapper);
        Add(persistence, "Tracking/I%A%Tracker.cs", Templates.TrackerPort);
        Add(persistence, "Tracking/%A%Tracker.cs", Templates.Tracker);
        Add(persistence, "Repositories/%A%Repository.cs", Templates.Repository);
        Add(persistence, "Queries/%A%Queries.cs", Templates.Queries);

        Add(api, "Controllers/%F%Controller.cs", Templates.Controller);
        Add(api, "Mapping/%A%ResponseMapping.cs", Templates.ResponseMapping);
        Add(api, "Contracts/Responses/%A%Response.cs", Templates.Response);

        return emissions;
    }

    /// <summary>
    /// Token substitution, and nothing cleverer: <c>%P%</c> the product prefix, <c>%F%</c> the
    /// feature folder, <c>%A%</c> the aggregate type.
    /// </summary>
    private static string Fill(string template, string prefix, string feature, string aggregate) =>
        template
            .Replace("%P%", prefix, StringComparison.Ordinal)
            .Replace("%F%", feature, StringComparison.Ordinal)
            .Replace("%A%", aggregate, StringComparison.Ordinal)
            .Replace("%L%", char.ToLowerInvariant(aggregate[0]) + aggregate[1..], StringComparison.Ordinal)
            .Replace("%R%", Kebab(feature), StringComparison.Ordinal);

    /// <summary>A PascalCase folder name as the route segment a caller sees: TodoLists, todo-lists.</summary>
    private static string Kebab(string pascal) =>
        string.Concat(pascal.Select((character, index) =>
            char.IsUpper(character) && index > 0
                ? "-" + char.ToLowerInvariant(character)
                : char.ToLowerInvariant(character).ToString()));


    /// <summary>
    /// Generates one vertical into a throwaway tree and checks the invariants this tool is
    /// responsible for: the ones an architecture rule would fail on later, read here instead.
    /// </summary>
    private static int SelfTest()
    {
        string root = Path.Combine(Path.GetTempPath(), "newfeature-selftest-" + Guid.CreateVersion7().ToString("N"));
        var problems = new List<string>();

        try
        {
            Directory.CreateDirectory(Path.Combine(root, "Src", "Domain", "Acme.Domain"));

            string prefix = ProductPrefix(root);

            if (!string.Equals(prefix, "Acme", StringComparison.Ordinal))
            {
                problems.Add($"The product prefix was read as '{prefix}' rather than 'Acme'.");
            }

            var emissions = Plan(prefix, "Widgets", "Widget");

            if (emissions.Count < 20)
            {
                problems.Add($"Only {emissions.Count} files planned; a vertical is more than that.");
            }

            foreach (var emission in emissions)
            {
                Write(Path.Combine(root, emission.Path), emission.Content);
            }

            foreach (var emission in emissions)
            {
                problems.AddRange(FileProblems(root, emission.Path));
            }

            // A token left unreplaced is the failure this tool would ship silently.
            foreach (var emission in emissions.Where(candidate => candidate.Content.Contains('%', StringComparison.Ordinal)))
            {
                problems.Add($"{emission.Path}: a '%' survived substitution.");
            }

            // Scaffolding twice must refuse rather than overwrite.
            if (!Plan(prefix, "Widgets", "Widget").All(emission => File.Exists(Path.Combine(root, emission.Path))))
            {
                problems.Add("The second plan names files the first did not write, so the refusal cannot see them.");
            }

            if (NameProblems("widgets", "Widget").Count == 0)
            {
                problems.Add("A lowercase feature name was accepted.");
            }

            if (NameProblems("Widget", "Widget").Count == 0)
            {
                problems.Add("A feature and an aggregate with the same name were accepted.");
            }

            Console.WriteLine(
                $"Self-test: {emissions.Count} file(s) generated into a throwaway tree, "
                + $"{problems.Count} problem(s).");
        }
        finally
        {
            if (Directory.Exists(root))
            {
                Directory.Delete(root, recursive: true);
            }
        }

        if (problems.Count > 0)
        {
            foreach (string problem in problems)
            {
                Console.Error.WriteLine($"  {problem}");
            }

            return 1;
        }

        Console.WriteLine();
        Console.WriteLine("Every file carries a BOM and LF endings, its namespace is its project plus its");
        Console.WriteLine("folder path, and the type it declares is named exactly like the file.");

        return 0;
    }

    /// <summary>The three claims this tool makes about every file it writes.</summary>
    private static IEnumerable<string> FileProblems(string root, string relative)
    {
        string full = Path.Combine(root, relative);
        byte[] bytes = File.ReadAllBytes(full);

        if (bytes.Length < 3 || bytes[0] != 0xEF || bytes[1] != 0xBB || bytes[2] != 0xBF)
        {
            yield return $"{relative}: no UTF-8 BOM, which the build turns into an error that does not say so.";
        }

        string text = Encoding.UTF8.GetString(bytes, 3, bytes.Length - 3);

        if (text.Contains('\r', StringComparison.Ordinal))
        {
            yield return $"{relative}: a CR, where this tree is LF only.";
        }

        string[] segments = relative.Replace('\\', '/').Split('/');
        int projectIndex = Array.FindIndex(segments, segment => segment.Contains('.', StringComparison.Ordinal));
        string expected = string.Join('.', segments[projectIndex..^1]);

        if (!text.Contains($"namespace {expected};", StringComparison.Ordinal))
        {
            yield return $"{relative}: its namespace is not '{expected}', which is its project plus its folders.";
        }

        string stem = Path.GetFileNameWithoutExtension(relative);
        var declaration = Regex.Match(text, @"\b(?:class|interface|record)\s+([A-Za-z0-9_]+)");

        if (!declaration.Success || !string.Equals(declaration.Groups[1].Value, stem, StringComparison.Ordinal))
        {
            yield return $"{relative}: declares '{(declaration.Success ? declaration.Groups[1].Value : "nothing")}' "
                + $"where the file is named '{stem}'.";
        }
    }

    private static void Report(string prefix, string feature, string aggregate, List<Emission> emissions)
    {
        Console.WriteLine($"Wrote {emissions.Count} files for {feature}/{aggregate}:");

        foreach (var emission in emissions)
        {
            Console.WriteLine($"  {emission.Path}");
        }

        Console.WriteLine();
        Console.WriteLine("It does not compose yet, and nothing here edited a file it does not own.");
        Console.WriteLine("Five edits, each by hand, each somewhere an absence should be visible:");
        Console.WriteLine();
        Console.WriteLine($"  1. {prefix}.Infrastructure.Persistence/Common/Contexts/AppDbContext.cs");
        Console.WriteLine($"     a '{feature}Schema' constant, an internal DbSet<{aggregate}Record>, and the");
        Console.WriteLine("     configuration applied in OnModelCreating");
        Console.WriteLine($"  2. {prefix}.Application/ApplicationModule.cs — an Add{feature}() registering the");
        Console.WriteLine($"     use cases, the validators and I{aggregate}Service");
        Console.WriteLine($"  3. {prefix}.Infrastructure.Persistence/PersistenceModule.cs — the mapper, the");
        Console.WriteLine("     tracker and the repository, the tracker registered once per scope under both");
        Console.WriteLine("     its own contract and IAggregateFlusher/IDomainEventSource");
        Console.WriteLine($"  4. Program.cs in each host that offers the feature — Add{feature}()");
        Console.WriteLine("  5. a migration: dotnet run Tools/Tasks.cs migration-add Add" + feature);
        Console.WriteLine();
        Console.WriteLine("Then the closed lists it lands in, which docs/ADDING-A-FEATURE.md section 5b");
        Console.WriteLine("enumerates with the reason each one exists:");
        Console.WriteLine();
        Console.WriteLine($"  - LayoutConventionTests — the folder words of {feature}/, in both directions");
        Console.WriteLine("  - FeatureFolderVocabularyTests — the feature folder");
        Console.WriteLine($"  - DomainModelTests._expectedEntities — {aggregate}");
        Console.WriteLine("  - DomainEventTests._deliberatelyUnconsumed — any event with no consumer");
        Console.WriteLine("  - HostComposition — the compositions a host builds");
        Console.WriteLine("  - the anti-vacuity floors you pass; raise them rather than leaving them behind");
        Console.WriteLine();
        Console.WriteLine("And the tests. Tests/ is a 1:1 mirror of Src/, and a scaffolded test asserts");
        Console.WriteLine("nothing — none is written here on purpose.");
    }
}

/// <summary>
/// The shapes, as text. Each is what its layer's conventions require and nothing more: no property
/// the domain has not been asked for, no rule nobody stated.
/// </summary>
internal static class Templates
{
    internal const string Aggregate = """
        using %P%.Domain.Core.Common.Abstractions;
        using %P%.Domain.Core.Common.Primitives;

        namespace %P%.Domain.Features.%F%.Entities;

        /// <summary>The aggregate root of the %F% feature, and its consistency boundary.</summary>
        public sealed class %A% : AuditableAggregateRoot<Guid>, IOwnedAggregate
        {
            private %A%(Guid id, UserId ownerId) : base(id)
            {
                ArgumentNullException.ThrowIfNull(ownerId);

                OwnerId = ownerId;
            }

            /// <inheritdoc />
            public UserId OwnerId { get; private set; }

            /// <summary>Mints a new one. Every invariant this aggregate has belongs here.</summary>
            public static %A% Create(UserId ownerId) => new(Guid.CreateVersion7(), ownerId);

            /// <summary>
            /// Rebuilds one from a stored row. Every invariant <see cref="Create"/> applies belongs
            /// here too: a row that violates one must be refused rather than become an aggregate
            /// that cannot honour its own rules.
            /// </summary>
            public static %A% Rehydrate(Guid id, UserId ownerId) => new(id, ownerId);
        }
        """;

    internal const string RepositoryPort = """
        using %P%.Domain.Features.%F%.Entities;

        namespace %P%.Domain.Features.%F%.Repositories;

        /// <summary>Stated in domain types only, which is why it lives here and not one layer out.</summary>
        public interface I%A%Repository
        {
            Task<%A%?> GetAsync(Guid id, CancellationToken cancellationToken);

            void Add(%A% aggregate);

            void Remove(%A% aggregate);
        }
        """;

    internal const string Errors = """
        using %P%.Application.Core.Common.Results;

        namespace %P%.Application.Features.%F%.Errors;

        /// <summary>The feature's failure vocabulary. Codes are stable; messages are not.</summary>
        public static class %A%Errors
        {
            public static Error %A%NotFound(Guid id) => Error.NotFound(
                "%L%.notFound",
                $"No %L% with id '{id}' was found.");
        }
        """;

    internal const string Dto = """
        namespace %P%.Application.Features.%F%.Dtos;

        /// <summary>What a read of one %A% answers with.</summary>
        public sealed record %A%Dto(Guid Id, Guid OwnerId, uint Version);
        """;

    internal const string QueriesPort = """
        using %P%.Application.Features.%F%.Dtos;
        using %P%.Domain.Core.Common.Primitives;

        namespace %P%.Application.Features.%F%.Ports.%A%Queries;

        /// <summary>
        /// The read side, projected straight to DTOs. Every method takes the owner: there is no
        /// overload and no sentinel that could stand for "everybody".
        /// </summary>
        public interface I%A%Queries
        {
            Task<%A%Dto?> GetAsync(UserId ownerId, Guid id, CancellationToken cancellationToken = default);
        }
        """;

    internal const string ServicePort = """
        using %P%.Application.Core.Common.Concurrency;
        using %P%.Application.Core.Common.Results;
        using %P%.Application.Features.%F%.Errors;
        using %P%.Domain.Features.%F%.Entities;

        namespace %P%.Application.Features.%F%.Services;

        /// <summary>
        /// The one gate every %A% command loads its aggregate through: identity, ownership and the
        /// version precondition, in that order.
        /// </summary>
        public interface I%A%Service
        {
            /// <returns>
            /// The aggregate, or a failure — <see cref="%A%Errors.%A%NotFound"/> for an anonymous
            /// caller, an unknown id or somebody else's, and
            /// <see cref="ConcurrencyErrors.PreconditionFailed"/> once ownership is established but
            /// the caller named a version the aggregate no longer holds.
            /// </returns>
            Task<Result<%A%>> LoadOwnedAsync(
                Guid id,
                VersionPrecondition? precondition,
                CancellationToken cancellationToken = default);
        }
        """;

    internal const string Service = """
        using %P%.Application.Core.Common.Concurrency;
        using %P%.Application.Core.Common.Ownership;
        using %P%.Application.Core.Common.Ports;
        using %P%.Application.Core.Common.Results;
        using %P%.Application.Features.%F%.Errors;
        using %P%.Domain.Features.%F%.Entities;
        using %P%.Domain.Features.%F%.Repositories;

        namespace %P%.Application.Features.%F%.Services;

        internal sealed class %A%Service(I%A%Repository repository, ICurrentUser currentUser) : I%A%Service
        {
            public async Task<Result<%A%>> LoadOwnedAsync(
                Guid id,
                VersionPrecondition? precondition,
                CancellationToken cancellationToken = default)
            {
                var userId = currentUser.RequireUserId();

                if (userId.IsFailure)
                {
                    return userId.To<%A%>();
                }

                return OwnedAggregate.Require(
                    await repository.GetAsync(id, cancellationToken),
                    userId.Value,
                    %A%Errors.%A%NotFound(id),
                    precondition);
            }
        }
        """;

    internal const string GetUseCasePort = """
        using %P%.Application.Core.Common.Results;
        using %P%.Application.Core.Common.UseCases;
        using %P%.Application.Features.%F%.Dtos;

        namespace %P%.Application.Features.%F%.UseCases.Queries.Get%A%;

        public interface IGet%A%UseCase : IUseCase<Guid, Result<%A%Dto>>;
        """;

    internal const string GetUseCase = """
        using %P%.Application.Core.Common.Ports;
        using %P%.Application.Core.Common.Results;
        using %P%.Application.Features.%F%.Dtos;
        using %P%.Application.Features.%F%.Errors;
        using %P%.Application.Features.%F%.Ports.%A%Queries;

        namespace %P%.Application.Features.%F%.UseCases.Queries.Get%A%;

        public sealed class Get%A%UseCase(I%A%Queries queries, ICurrentUser currentUser) : IGet%A%UseCase
        {
            public async Task<Result<%A%Dto>> ExecuteAsync(Guid id, CancellationToken cancellationToken = default)
            {
                var userId = currentUser.RequireUserId();

                if (userId.IsFailure)
                {
                    return userId.To<%A%Dto>();
                }

                var found = await queries.GetAsync(userId.Value, id, cancellationToken);

                return found is null
                    ? Result.Failure<%A%Dto>(%A%Errors.%A%NotFound(id))
                    : Result.Success(found);
            }
        }
        """;

    internal const string CreateUseCasePort = """
        using %P%.Application.Core.Common.Results;
        using %P%.Application.Core.Common.UseCases;

        namespace %P%.Application.Features.%F%.UseCases.Commands.Create%A%;

        public interface ICreate%A%UseCase : IUseCase<Result<Guid>>;
        """;

    internal const string CreateUseCase = """
        using %P%.Application.Core.Common.Ports;
        using %P%.Application.Core.Common.Results;
        using %P%.Domain.Features.%F%.Entities;
        using %P%.Domain.Features.%F%.Repositories;

        namespace %P%.Application.Features.%F%.UseCases.Commands.Create%A%;

        public sealed class Create%A%UseCase(
            I%A%Repository repository,
            ICurrentUser currentUser,
            IUnitOfWork unitOfWork) : ICreate%A%UseCase
        {
            public async Task<Result<Guid>> ExecuteAsync(CancellationToken cancellationToken = default)
            {
                var userId = currentUser.RequireUserId();

                if (userId.IsFailure)
                {
                    return userId.To<Guid>();
                }

                var aggregate = %A%.Create(userId.Value);

                repository.Add(aggregate);
                await unitOfWork.SaveChangesAsync(cancellationToken);

                return Result.Success(aggregate.Id);
            }
        }
        """;

    internal const string DeleteCommand = """
        using %P%.Application.Core.Common.Concurrency;

        namespace %P%.Application.Features.%F%.UseCases.Commands.Delete%A%;

        public sealed record Delete%A%Command(Guid Id, VersionPrecondition? Precondition = null);
        """;

    internal const string DeleteUseCasePort = """
        using %P%.Application.Core.Common.Results;
        using %P%.Application.Core.Common.UseCases;

        namespace %P%.Application.Features.%F%.UseCases.Commands.Delete%A%;

        public interface IDelete%A%UseCase : IUseCase<Delete%A%Command, Result>;
        """;

    internal const string DeleteUseCase = """
        using %P%.Application.Core.Common.Ports;
        using %P%.Application.Core.Common.Results;
        using %P%.Application.Features.%F%.Services;
        using %P%.Domain.Features.%F%.Repositories;

        namespace %P%.Application.Features.%F%.UseCases.Commands.Delete%A%;

        public sealed class Delete%A%UseCase(
            I%A%Service %L%s,
            I%A%Repository repository,
            IUnitOfWork unitOfWork) : IDelete%A%UseCase
        {
            public async Task<Result> ExecuteAsync(
                Delete%A%Command command,
                CancellationToken cancellationToken = default)
            {
                ArgumentNullException.ThrowIfNull(command);

                var loaded = await %L%s.LoadOwnedAsync(command.Id, command.Precondition, cancellationToken);

                if (loaded.IsFailure)
                {
                    return loaded;
                }

                repository.Remove(loaded.Value);
                await unitOfWork.SaveChangesAsync(cancellationToken);

                return Result.Success();
            }
        }
        """;

    internal const string DeleteValidator = """
        using FluentValidation;

        namespace %P%.Application.Features.%F%.UseCases.Commands.Delete%A%;

        public sealed class Delete%A%CommandValidator : AbstractValidator<Delete%A%Command>
        {
            public Delete%A%CommandValidator() =>
                RuleFor(command => command.Id)
                    .NotEmpty().WithMessage("An id is required.");
        }
        """;

    internal const string Record = """
        using %P%.Domain.Core.Common.Abstractions;

        namespace %P%.Infrastructure.Persistence.Features.%F%.Models;

        internal sealed class %A%Record : IAuditable
        {
            public Guid Id { get; set; }

            public Guid OwnerId { get; set; }

            public uint Version { get; set; }

            public DateTimeOffset CreatedAt { get; set; }

            public Guid? CreatedBy { get; set; }

            public DateTimeOffset? LastModifiedAt { get; set; }

            public Guid? LastModifiedBy { get; set; }

            void IAuditable.SetCreated(DateTimeOffset at, Guid? by)
            {
                CreatedAt = at;
                CreatedBy = by;
            }

            void IAuditable.SetLastModified(DateTimeOffset at, Guid? by)
            {
                LastModifiedAt = at;
                LastModifiedBy = by;
            }
        }
        """;

    internal const string Configuration = """
        using %P%.Infrastructure.Persistence.Common.Contexts;
        using %P%.Infrastructure.Persistence.Features.%F%.Models;
        using Microsoft.EntityFrameworkCore;
        using Microsoft.EntityFrameworkCore.Metadata.Builders;

        namespace %P%.Infrastructure.Persistence.Features.%F%.Configurations;

        internal sealed class %A%RecordConfiguration : IEntityTypeConfiguration<%A%Record>
        {
            public void Configure(EntityTypeBuilder<%A%Record> builder)
            {
                ArgumentNullException.ThrowIfNull(builder);

                builder.ToTable("%F%", AppDbContext.%F%Schema);
                builder.HasKey(record => record.Id);

                // Ids are UUIDv7, created by the domain.
                builder.Property(record => record.Id).ValueGeneratedNever();
                builder.Property(record => record.OwnerId).IsRequired();

                builder.HasIndex(record => record.OwnerId)
                    .HasDatabaseName("IX_%F%_OwnerId");

                // PostgreSQL's xmin system column, which already exists: EF reads it back after a
                // write and puts it in the WHERE clause of the next one.
                builder.Property(record => record.Version)
                    .HasColumnName("xmin")
                    .HasColumnType("xid")
                    .ValueGeneratedOnAddOrUpdate()
                    .IsConcurrencyToken();

                builder.Property(record => record.CreatedAt).IsRequired();
                builder.Property(record => record.CreatedBy);
                builder.Property(record => record.LastModifiedAt);
                builder.Property(record => record.LastModifiedBy);
            }
        }
        """;

    internal const string MapperPort = """
        using %P%.Domain.Features.%F%.Entities;
        using %P%.Infrastructure.Persistence.Features.%F%.Models;

        namespace %P%.Infrastructure.Persistence.Features.%F%.Mapping;

        internal interface I%A%Mapper
        {
            %A% ToAggregate(%A%Record record);

            %A%Record ToNewRecord(%A% aggregate);

            void WriteTo(%A% aggregate, %A%Record record);
        }
        """;

    internal const string Mapper = """
        using %P%.Domain.Core.Common.Primitives;
        using %P%.Domain.Features.%F%.Entities;
        using %P%.Infrastructure.Core.Common.Saving.Tracking;
        using %P%.Infrastructure.Persistence.Features.%F%.Models;

        namespace %P%.Infrastructure.Persistence.Features.%F%.Mapping;

        internal sealed class %A%Mapper : I%A%Mapper
        {
            public %A% ToAggregate(%A%Record record)
            {
                ArgumentNullException.ThrowIfNull(record);

                var aggregate = %A%.Rehydrate(record.Id, UserId.Create(record.OwnerId));

                StoredStamps.ApplyTo(aggregate, record, record.Version, record.Id, "%A%");

                return aggregate;
            }

            public %A%Record ToNewRecord(%A% aggregate)
            {
                ArgumentNullException.ThrowIfNull(aggregate);

                return new %A%Record
                {
                    Id = aggregate.Id,
                    OwnerId = aggregate.OwnerId.Value,

                    // Overwritten on insert, where PostgreSQL assigns xmin. Carried so the round
                    // trip stays total and the fidelity test can check it.
                    Version = aggregate.Version,

                    // Overwritten by the audit interceptor, which runs after this.
                    CreatedAt = aggregate.CreatedAt,
                    CreatedBy = aggregate.CreatedBy,
                    LastModifiedAt = aggregate.LastModifiedAt,
                    LastModifiedBy = aggregate.LastModifiedBy,
                };
            }

            public void WriteTo(%A% aggregate, %A%Record record)
            {
                ArgumentNullException.ThrowIfNull(aggregate);
                ArgumentNullException.ThrowIfNull(record);

                record.OwnerId = aggregate.OwnerId.Value;
            }
        }
        """;

    internal const string TrackerPort = """
        using %P%.Domain.Features.%F%.Entities;
        using %P%.Infrastructure.Core.Common.Saving.DomainEvents;
        using %P%.Infrastructure.Core.Common.Saving.Tracking;
        using %P%.Infrastructure.Persistence.Features.%F%.Models;

        namespace %P%.Infrastructure.Persistence.Features.%F%.Tracking;

        internal interface I%A%Tracker : IAggregateFlusher, IDomainEventSource
        {
            %A%? Find(Guid id);

            void Track(%A% aggregate, %A%Record record);

            %A%Record? FindRecord(Guid id);

            void MarkRemoved(%A% aggregate, %A%Record record);
        }
        """;

    internal const string Tracker = """
        using %P%.Domain.Features.%F%.Entities;
        using %P%.Infrastructure.Core.Common.Saving.Tracking;
        using %P%.Infrastructure.Persistence.Features.%F%.Mapping;
        using %P%.Infrastructure.Persistence.Features.%F%.Models;
        using Microsoft.EntityFrameworkCore;

        namespace %P%.Infrastructure.Persistence.Features.%F%.Tracking;

        internal sealed class %A%Tracker(I%A%Mapper mapper)
            : AggregateTracker<%A%, %A%Record>(record => record.Version), I%A%Tracker
        {
            public override void FlushTo(DbContext context)
            {
                ArgumentNullException.ThrowIfNull(context);

                foreach (var tracked in TrackedAggregates)
                {
                    var entry = context.Entry(tracked.Record);

                    // A Deleted entry would resurrect columns EF is about to drop, and a Detached
                    // one would silently take the write.
                    if (tracked.IsRemoved || entry.State is EntityState.Deleted or EntityState.Detached)
                    {
                        continue;
                    }

                    mapper.WriteTo(tracked.Aggregate, tracked.Record);

                    if (entry.State != EntityState.Added)
                    {
                        // Setting the original value does not mark the property modified, so this
                        // reaches the WHERE clause only.
                        entry.Property(record => record.Version).OriginalValue = tracked.Aggregate.Version;
                    }
                }
            }
        }
        """;

    internal const string Repository = """
        using %P%.Domain.Features.%F%.Entities;
        using %P%.Domain.Features.%F%.Repositories;
        using %P%.Infrastructure.Persistence.Common.Contexts;
        using %P%.Infrastructure.Persistence.Features.%F%.Mapping;
        using %P%.Infrastructure.Persistence.Features.%F%.Models;
        using %P%.Infrastructure.Persistence.Features.%F%.Tracking;
        using Microsoft.EntityFrameworkCore;

        namespace %P%.Infrastructure.Persistence.Features.%F%.Repositories;

        internal sealed class %A%Repository(
            AppDbContext context,
            I%A%Mapper mapper,
            I%A%Tracker tracker) : I%A%Repository
        {
            public async Task<%A%?> GetAsync(Guid id, CancellationToken cancellationToken)
            {
                // The identity map first: two use cases in one request must get the same object, or
                // the flush would keep whichever copy it saw last.
                if (tracker.Find(id) is { } alreadyLoaded)
                {
                    return alreadyLoaded;
                }

                var record = await context.%F%.FirstOrDefaultAsync(
                    candidate => candidate.Id == id,
                    cancellationToken);

                return record is null ? null : LoadOrTrack(record);
            }

            public void Add(%A% aggregate)
            {
                ArgumentNullException.ThrowIfNull(aggregate);

                var record = mapper.ToNewRecord(aggregate);

                context.%F%.Add(record);
                tracker.Track(aggregate, record);
            }

            public void Remove(%A% aggregate)
            {
                ArgumentNullException.ThrowIfNull(aggregate);

                if (tracker.FindRecord(aggregate.Id) is not { } record)
                {
                    return;
                }

                context.%F%.Remove(record);
                tracker.MarkRemoved(aggregate, record);
            }

            private %A% LoadOrTrack(%A%Record record)
            {
                var aggregate = mapper.ToAggregate(record);

                tracker.Track(aggregate, record);

                return aggregate;
            }
        }
        """;

    internal const string Queries = """
        using %P%.Application.Features.%F%.Dtos;
        using %P%.Application.Features.%F%.Ports.%A%Queries;
        using %P%.Domain.Core.Common.Primitives;
        using %P%.Infrastructure.Persistence.Common.Contexts;
        using Microsoft.EntityFrameworkCore;

        namespace %P%.Infrastructure.Persistence.Features.%F%.Queries;

        internal sealed class %A%Queries(AppDbContext context) : I%A%Queries
        {
            public Task<%A%Dto?> GetAsync(
                UserId ownerId,
                Guid id,
                CancellationToken cancellationToken = default)
            {
                ArgumentNullException.ThrowIfNull(ownerId);

                return context.%F%
                    .AsNoTracking()
                    .Where(record => record.Id == id && record.OwnerId == ownerId.Value)
                    .Select(record => new %A%Dto(record.Id, record.OwnerId, record.Version))
                    .FirstOrDefaultAsync(cancellationToken);
            }
        }
        """;

    internal const string Response = """
        namespace %P%.Api.Features.%F%.Contracts.Responses;

        /// <summary>One %A%, as a caller sees it.</summary>
        /// <param name="Id">Its identifier.</param>
        /// <param name="OwnerId">Whose it is.</param>
        public sealed record %A%Response(Guid Id, Guid OwnerId);
        """;

    internal const string ResponseMapping = """
        using %P%.Api.Features.%F%.Contracts.Responses;
        using %P%.Application.Core.Common.Results;
        using %P%.Application.Features.%F%.Dtos;

        namespace %P%.Api.Features.%F%.Mapping;

        internal static class %A%ResponseMapping
        {
            internal static Result<%A%Response> To%A%Response(Result<%A%Dto> result) =>
                result.Map(dto => new %A%Response(dto.Id, dto.OwnerId));
        }
        """;

    internal const string Controller = """
        using %P%.Api.Core.Common.Controllers;
        using %P%.Api.Core.Common.Idempotency;
        using %P%.Api.Features.%F%.Contracts.Responses;
        using %P%.Api.Features.%F%.Mapping;
        using %P%.Application.Features.%F%.UseCases.Commands.Create%A%;
        using %P%.Application.Features.%F%.UseCases.Commands.Delete%A%;
        using %P%.Application.Features.%F%.UseCases.Queries.Get%A%;
        using Microsoft.AspNetCore.Mvc;

        namespace %P%.Api.Features.%F%.Controllers;

        [Route("api/v{version:apiVersion}/%R%")]
        [Asp.Versioning.ApiVersion("1.0")]
        [ProducesResponseType(StatusCodes.Status401Unauthorized, Type = typeof(ProblemDetails))]
        public sealed class %F%Controller(
            IGet%A%UseCase get%A%,
            ICreate%A%UseCase create%A%,
            IDelete%A%UseCase delete%A%) : ApiControllerBase
        {
            [HttpGet("{id:guid}", Name = nameof(Get))]
            [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(%A%Response))]
            [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(ProblemDetails))]
            public async Task<ActionResult<%A%Response>> Get(Guid id, CancellationToken cancellationToken) =>
                OkOrProblem(%A%ResponseMapping.To%A%Response(await get%A%.ExecuteAsync(id, cancellationToken)));

            [HttpPost]
            [Idempotent]
            [ProducesResponseType(StatusCodes.Status201Created, Type = typeof(Guid))]
            [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(ValidationProblemDetails))]
            public async Task<ActionResult<Guid>> Create(CancellationToken cancellationToken)
            {
                var created = await create%A%.ExecuteAsync(cancellationToken);

                // The lambda is typed rather than inferred: CreatedOrProblem has an overload
                // taking a plain object, so an untyped one is ambiguous.
                return CreatedOrProblem(created, nameof(Get), (Guid id) => new { id });
            }

            [HttpDelete("{id:guid}")]
            [ProducesResponseType(StatusCodes.Status204NoContent)]
            [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(ProblemDetails))]
            [ProducesResponseType(StatusCodes.Status409Conflict, Type = typeof(ProblemDetails))]
            public async Task<IActionResult> Delete(Guid id, CancellationToken cancellationToken) =>
                NoContentOrProblem(await delete%A%.ExecuteAsync(new Delete%A%Command(id), cancellationToken));
        }
        """;
}
